In [1]:
import numpy as np
import math

In [2]:
def lu(A):
  n = A.shape[0]
  P = np.eye(n)
  L = np.zeros((n, n))
  U = A.copy().astype(float)

  for k in range(n):
    max_index = np.argmax(abs(U[k:, k])) + k
    if k != max_index:
      U[[k, max_index]] = U[[max_index, k]]
      P[[k, max_index]] = P[[max_index, k]]
      L[[k, max_index]] = L[[max_index, k]]

    for i in range(k+1, n):
      L[i][k] = U[i][k] / U[k][k]
      U[i][k:] = U[i][k:] - L[i][k] * U[k][k:]

    np.fill_diagonal(L, 1)
    return P, L, U

In [4]:
A = np.array([[2, 3, 1],
              [4, 7, 7],
              [6, 18, 22]], dtype=float)

P, L, U = lu(A)

print("P:\n", P)
print("L:\n", L)
print("U:\n", U)

# Check result
print("Check PA == LU:\n", np.allclose(P @ A, L @ U))


P:
 [[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
L:
 [[1.         0.         0.        ]
 [0.66666667 1.         0.        ]
 [0.33333333 0.         1.        ]]
U:
 [[ 6.         18.         22.        ]
 [ 0.         -5.         -7.66666667]
 [ 0.         -3.         -6.33333333]]
Check PA == LU:
 True
